/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        primary: '#004cca',
        'primary-container': '#0062ff',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#f3f3ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'inverse-primary': '#b4c5ff',
        secondary: '#425ba1',
        'secondary-container': '#99b1fd',
        'secondary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b4c5ff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#274186',
        'on-secondary-fixed': '#00174b',
        'on-secondary-fixed-variant': '#294388',
        tertiary: '#9e3100',
        'tertiary-container': '#c84000',
        'tertiary-fixed': '#ffdbcf',
        'tertiary-fixed-dim': '#ffb59c',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fff1ed',
        'on-tertiary-fixed': '#390c00',
        'on-tertiary-fixed-variant': '#832700',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-tint': '#0053da',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#424656',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#737687',
        'outline-variant': '#c2c6d9',
        'background-light': '#f5f6f8',
        'background-dark': '#0f1723',
      },
      fontFamily: {
        display: ['Manrope', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
